apiVersion: v1
kind: Secret
metadata:
  name: task-master-api-keys
  namespace: task-master-ai
  labels:
    app.kubernetes.io/name: task-master-ai
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # OpenAI API Key (Base64 encoded)
  openai-api-key: "c2stc3ZjYWNjdC1KWG5QTWxPNFFhNWJEejZvVl9BTHhYY3dKdlNtdWpaeS1CbEhNd0luM1VwZDk0UldkUEg1V2g5V3RNa3oyZ0I5SENMQjVIa0RpNFQzQmxia0ZKREpYUk9sNFpnSjFGVnlqbzQ2WEVidU9vSnktOUhaMENJTnUyLVdnampEZTZUWFBtSDY4QW9OOHpqU1FjckJ3cENFWXExTVhvQUE="
  
  # Perplexity API Key (Base64 encoded)  
  perplexity-api-key: "cHBseC1CYVM4elI5VjVBOUllUTJaWmd2cVhjREI5cWdGZTVYdzQxeWVWcERXc3VpVEVtUWM="
  
  # Placeholder for future keys
  anthropic-api-key: "UkVQTEFDRV9XSVRIX0FDVFVBTF9BTlRIUk9QSUNfS0VZ"
  
  # echo -n "your_google_api_key" | base64 (optional)
  google-api-key: "UkVQTEFDRV9XSVRIX0FDVFVBTF9HT09HTEVfS0VZ"

---
apiVersion: v1
kind: Secret
metadata:
  name: task-master-github-token
  namespace: task-master-ai
  labels:
    app.kubernetes.io/name: task-master-ai
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # echo -n "your_github_token" | base64
  github-token: "UkVQTEFDRV9XSVRIX0FDVFVBTF9HSVRIVUJfVE9LRU4="

---
apiVersion: v1
kind: Secret
metadata:
  name: task-master-database
  namespace: task-master-ai
  labels:
    app.kubernetes.io/name: task-master-ai
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Database credentials for persistent storage (if using external DB)
  # echo -n "database_url" | base64
  database-url: "UkVQTEFDRV9XSVRIX0FDVFVBTF9EQVRBQkFTRV9VUkw="
  
  # echo -n "database_username" | base64
  database-username: "UkVQTEFDRV9XSVRIX0FDVFVBTF9EQl9VU0VSTkFNRQ=="
  
  # echo -n "database_password" | base64
  database-password: "UkVQTEFDRV9XSVRIX0FDVFVBTF9EQl9QQVNTV09SRA=="